### ISSUE TITLE
Issue respective to git

### ISSUE THREAD

**Issue by sheikalthaf** [withastro/houston-vscode#5]
Thanks for the awesome theme, found some issue after installing for the first time

https://user-images.githubusercontent.com/22526247/208661352-ea5919fa-0710-4609-989f-2c6dee9550e6.mov

scrollbar is hiding the difference indicator

https://user-images.githubusercontent.com/22526247/208661546-05025b3c-7587-47da-8cb8-ae9b24e479df.mov

Selected text is not visible

**Comment by sheikalthaf** [comment]
<img width="891" alt="image" src="https://user-images.githubusercontent.com/22526247/208685165-e944643b-723d-44a9-9326-84e4deb1b1a4.png">

The params names are more brighter that the values, It is possible to reduces their colors dark

**Comment by VoxelMC** [comment]
Hello @sheikalthaf! I am going to start working on this issue, but I have a few questions.

First, I think I have fixed the first problem, let me know what you think about it:

https://github.com/withastro/houston-vscode/assets/20650404/e9c9341f-454c-4fd6-9490-61e3ef521167

Second, I am not sure what you mean here:
> scrollbar is hiding the difference indicator

It seems visible to me, however the contrast *is* quite low. If it is not visible on your screen due to contrast issues, we can look into possible changes here, together :)

Last, I would love a bit more explanation for what you say here:
> The params names are more brighter that the values, It is possible to reduces their colors dark

In this context, what do you refer to as the `values`?
